### ISSUE TITLE
Update the plugin to support all components

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml-syntax#1]

**Comment by arthurkatz** [comment]
Hello @ngarnier,
Do you think we can close this issue ? 
If you want to add something more please tell me maybe I can help, although i'm not using sublime text as my default IDE :D

**Comment by ngarnier** [comment]
You're right, I'm closing! Thanks again for your help, the plugin is available here: https://packagecontrol.io/packages/MJML-syntax
