### ISSUE TITLE
Indentation hardcoded to 4 spaces

### ISSUE THREAD

**Issue by joshuabaker** [mjmlio/mjml-syntax#11]
From the snippet docs:
> When writing a snippet that contains indentation, always use tabs. The tabs will be transformed into spaces when the snippet is inserted if the option translateTabsToSpaces is set to true.

**Comment by ngarnier** [comment]
Hey @joshuabaker, thanks for pasting a piece of the documentation but you can be a little more explicit on what the issue is please? 🙃

**Comment by joshuabaker** [comment]
@ngarnier Sorry. I realise in hindsight that the issue title is probably not sufficient. 😅 

I indent by 2 spaces normally, however, `mjml-syntax` is hardcoded to intent by 4 spaces.

I _think_ that the referenced documentation is saying that hardcoding a tab instead of spaces should automatically resolve to the user’s preference.

**Comment by ngarnier** [comment]
Ah indeed, thanks for reporting. Feel free to make a PR to fix this!

**Comment by joshuabaker** [comment]
I’d normally wade in with a PR, however, I can’t figure out how to test this locally. Will try and figure it out.
