### ISSUE TITLE
[Fixed] Not working with Sublime Text 4

### ISSUE THREAD

**Issue by ced64k** [mjmlio/mjml-syntax#14]
The package is not working with Sublime Text 4 build 4107

`Error loading syntax file "Packages/MJML-syntax/MJML.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

**Comment by ced64k** [comment]
Working with Sublime Text 4 4121

**Comment by zedtux** [comment]
Hey @ced64k I'm using the same build version, but I have the same error as you posted in your initial comment.

Is it still working?

**Comment by ced64k** [comment]
Hi @zedtux it's weird because I didn't get the error on my work computer and still have the error on my home computer. Both with 4121. Maybe it's a conflict with another Sublime Text extension ?

**Comment by zedtux** [comment]
> Maybe it's a conflict with another Sublime Text extension ?

I fully agree with you.

**Comment by ced64k** [comment]
@zedtux It's coming from JavaScriptNext ES6 Syntax, when I removed this package the error with MJML disappears :)

**Comment by zedtux** [comment]
Well I don't have this package installed, so there's another conflicting package. I wouldn't have updated the title with "Fixed". 😉
