### ISSUE TITLE
Keyboard Short-cuts

### ISSUE THREAD

**Issue by macleanja88** [mjmlio/mjml-syntax#8]
Wondering if I could get a list of shortcuts for the MJML app.

**Comment by ngarnier** [comment]
hey @macleanja88, this is the repository for the Sublime Text package. Do you mean shortcuts for the Sublime Text package or for the [MJML desktop app](https://github.com/mjmlio/mjml-app)?

**Comment by macleanja88** [comment]
I meant for the MJML desktop app

**Comment by macleanja88** [comment]
@ngarnier

**Comment by ngarnier** [comment]
hey @macleanja88, you can find an answer on the mjml-app repo: https://github.com/mjmlio/mjml-app/issues/221
