### ISSUE TITLE
For vscode, commenting outputs '// ' instead of '<!--  -->'

### ISSUE THREAD

**Issue by urbgimtam** [mjmlio/mjml-syntax#9]
To solve this, I had to disable the 
    `"lineComment": "//", `
line in **language-configuration.json** file, directly in the extensions folder.

**Comment by iRyusa** [comment]
Well this is not the vscode repo: https://github.com/attilabuti/vscode-mjml

**Comment by urbgimtam** [comment]
I'm sorry. You are right, of course. 
I've added an issue in the wrong browser window :)
